name: kiss_firebase_repository_example
description: "An example project for the kiss_firebase_repository package."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  # Add our package as a dependency
  kiss_firebase_repository:
    path: ../
  # Firebase dependencies
  firebase_core: ^3.13.1
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

