name: kiss_firebase_repository
description: "A firebase implementation of kiss_repository interface"
version: 0.8.0
homepage: https://github.com/WAMF/kiss_firebase_repository

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  
  kiss_repository:
    path: ../kiss_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  kiss_repository_tests:
    path: ../kiss_repository_tests

